import Card from "../ui/Card.jsx";
import CopyButton from "../ui/CopyButton.jsx";
import ExportButton from "../ui/ExportButton.jsx";
import ArchitectureDiagram from "./ArchitectureDiagram.jsx";
import FolderTree from "./FolderTree.jsx";
import SchemaVisualizer from "./SchemaVisualizer.jsx";
import ApiFlowDiagram from "./ApiFlowDiagram.jsx";
import React from "react";

function SectionHeader({ title, children }) {
  return (
    <div className="mb-4 flex items-center justify-between">
      <h3 className="text-lg font-semibold text-slate-950 dark:text-white">{title}</h3>
      <div className="flex gap-2">{children}</div>
    </div>
  );
}

export default function ProjectDetails({ project }) {
  const copyAllText = JSON.stringify(project, null, 2);

  return (
    <div className="space-y-5">
      <Card className="p-6">
        <div className="flex flex-wrap items-center gap-3">
          <h2 className="text-2xl font-bold text-slate-950 dark:text-white">
            {project.title}
          </h2>

          {project.source && (
            <span
              className={`rounded-full px-3 py-1 text-xs font-semibold ${
                project.source === "gemini"
                  ? "bg-purple-100 text-purple-700 dark:bg-purple-900/50 dark:text-purple-300"
                  : "bg-amber-100 text-amber-700 dark:bg-amber-900/50 dark:text-amber-300"
              }`}
            >
              {project.sourceType === "analyzed"
                ? (project.source === "gemini" ? "Analyzed by Gemini AI" : "Analyzed (Template)")
                : (project.source === "gemini" ? "Generated By Gemini AI" : "Template Fallback")}
            </span>
          )}
        </div>

        <p className="mt-4 leading-7 text-slate-600 dark:text-slate-400">
          {project.description}
        </p>

        <div className="mt-5 flex flex-wrap gap-2">
          <span className="rounded-full bg-indigo-50 px-3 py-1 text-sm font-semibold text-indigo-700 dark:bg-indigo-900/50 dark:text-indigo-300">
            {project.domain}
          </span>

          <span className="rounded-full bg-slate-100 px-3 py-1 text-sm font-semibold text-slate-700 dark:bg-slate-800 dark:text-slate-300">
            {project.difficulty}
          </span>

          <span className="rounded-full bg-emerald-50 px-3 py-1 text-sm font-semibold text-emerald-700 dark:bg-emerald-900/50 dark:text-emerald-300">
            {project.estimatedTime}
          </span>
        </div>

        {project.complexityScore !== undefined && (
          <div className="mt-5">
            <div className="flex items-center justify-between text-sm">
              <span className="font-semibold text-slate-700 dark:text-slate-300">Complexity Score</span>
              <span className="font-bold text-indigo-600 dark:text-indigo-400">
                {project.complexityScore}/100 - {project.complexityScore <= 40 ? "Beginner" : project.complexityScore <= 70 ? "Intermediate" : "Advanced"}
              </span>
            </div>
            <div className="mt-2 h-3 w-full rounded-full bg-slate-200 dark:bg-slate-700">
              <div
                className="h-3 rounded-full bg-gradient-to-r from-indigo-500 to-purple-600 transition-all"
                style={{ width: `${project.complexityScore}%` }}
              />
            </div>
          </div>
        )}

        <div className="mt-5 flex flex-wrap gap-2">
          <ExportButton project={project} />
          <CopyButton text={copyAllText} label="Copy All" />
        </div>
      </Card>

      {project.architecture && (
        <Card className="p-6">
          <SectionHeader title="Architecture">
            <CopyButton text={project.architecture} label="Copy Architecture" />
          </SectionHeader>

          <ArchitectureDiagram project={project} />

          <div className="mt-4 rounded-lg bg-slate-50 p-4 dark:bg-slate-800">
            <pre className="whitespace-pre-wrap text-sm text-slate-700 dark:text-slate-300">
              {project.architecture}
            </pre>
          </div>
        </Card>
      )}

      <div className="grid gap-5 lg:grid-cols-2">
        <Card className="p-6">
          <SectionHeader title="Core Features">
            <CopyButton text={project.features?.join("\n")} label="Copy" />
          </SectionHeader>

          <ul className="space-y-3 text-sm text-slate-700 dark:text-slate-300">
            {project.features?.map((feature, index) => (
              <li
                key={index}
                className="rounded-md border border-slate-200 px-3 py-2 dark:border-slate-700"
              >
                {feature}
              </li>
            ))}
          </ul>
        </Card>

        <Card className="p-6">
          <SectionHeader title="Recommended Tech Stack">
            <CopyButton text={project.techStack?.join(", ")} label="Copy" />
          </SectionHeader>

          <div className="flex flex-wrap gap-2">
            {project.techStack?.map((tech, index) => (
              <span
                key={index}
                className="rounded-md bg-slate-100 px-3 py-2 text-sm font-medium text-slate-700 dark:bg-slate-800 dark:text-slate-300"
              >
                {tech}
              </span>
            ))}
          </div>
        </Card>
      </div>

      {project.databaseSchema?.length > 0 && (
        <Card className="p-6">
          <SectionHeader title="Database Schema">
            <CopyButton
              text={project.databaseSchema.map(s => `Collection: ${s.collection}\n${s.fields?.map(f => `  - ${f.name} (${f.type}): ${f.description}`).join("\n")}`).join("\n\n")}
              label="Copy Schema"
            />
          </SectionHeader>

          <SchemaVisualizer schema={project.databaseSchema} />

          <div className="mt-4 space-y-5">
            {project.databaseSchema.map((collection, index) => (
              <div
                key={index}
                className="rounded-lg border border-slate-200 p-4 dark:border-slate-700"
              >
                <h4 className="mb-3 font-semibold text-indigo-700 dark:text-indigo-400">
                  {collection.collection}
                </h4>

                <div className="space-y-2">
                  {collection.fields?.map((field, idx) => (
                    <div
                      key={idx}
                      className="rounded bg-slate-50 p-2 text-sm dark:bg-slate-800"
                    >
                      <strong className="text-slate-900 dark:text-white">{field.name}</strong>

                      {field.type && (
                        <span className="ml-2 text-slate-500 dark:text-slate-400">
                          ({field.type})
                        </span>
                      )}

                      {field.description && (
                        <p className="mt-1 text-slate-600 dark:text-slate-400">
                          {field.description}
                        </p>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </Card>
      )}

      {project.apiEndpoints?.length > 0 && (
        <Card className="p-6">
          <SectionHeader title="API Endpoints">
            <CopyButton
              text={project.apiEndpoints.map(e => `${e.method} ${e.endpoint} - ${e.description}`).join("\n")}
              label="Copy APIs"
            />
          </SectionHeader>

          <ApiFlowDiagram endpoints={project.apiEndpoints} />

          <div className="mt-4 space-y-3">
            {project.apiEndpoints.map((api, index) => (
              <div
                key={index}
                className="rounded-lg border border-slate-200 p-4 dark:border-slate-700"
              >
                <div className="flex flex-wrap items-center gap-3">
                  <span className="rounded bg-green-100 px-2 py-1 text-xs font-bold text-green-700 dark:bg-green-900/50 dark:text-green-300">
                    {api.method}
                  </span>

                  <code className="text-sm font-medium text-slate-900 dark:text-white">
                    {api.endpoint}
                  </code>
                </div>

                <p className="mt-2 text-sm text-slate-600 dark:text-slate-400">
                  {api.description}
                </p>
              </div>
            ))}
          </div>
        </Card>
      )}

      <div className="grid gap-5 lg:grid-cols-2">
        {project.folderStructure?.length > 0 && (
          <Card className="p-6">
            <SectionHeader title="Folder Structure">
              <CopyButton text={project.folderStructure?.join("\n")} label="Copy" />
            </SectionHeader>

            <FolderTree folders={project.folderStructure} />

            <div className="mt-4 space-y-2">
              {project.folderStructure.map((folder, index) => (
                <div
                  key={index}
                  className="rounded bg-slate-50 px-3 py-2 font-mono text-sm text-slate-700 dark:bg-slate-800 dark:text-slate-300"
                >
                  {folder}
                </div>
              ))}
            </div>
          </Card>
        )}

        {project.roadmap?.length > 0 && (
          <Card className="p-6">
            <SectionHeader title="Development Roadmap">
              <CopyButton text={project.roadmap?.map((s, i) => `${i + 1}. ${s}`).join("\n")} label="Copy" />
            </SectionHeader>

            <ol className="space-y-3">
              {project.roadmap.map((step, index) => (
                <li
                  key={index}
                  className="flex gap-3 rounded border border-slate-200 p-3 text-slate-700 dark:border-slate-700 dark:text-slate-300"
                >
                  <span className="font-bold text-indigo-700 dark:text-indigo-400">
                    {index + 1}.
                  </span>

                  <span>{step}</span>
                </li>
              ))}
            </ol>
          </Card>
        )}
      </div>

      {project.resumePoints?.length > 0 && (
        <Card className="p-6">
          <SectionHeader title="Resume Points">
            <CopyButton text={project.resumePoints?.map(p => `• ${p}`).join("\n")} label="Copy Points" />
          </SectionHeader>

          <ul className="space-y-3">
            {project.resumePoints.map((point, index) => (
              <li
                key={index}
                className="rounded border border-slate-200 p-3 text-slate-700 dark:border-slate-700 dark:text-slate-300"
              >
                • {point}
              </li>
            ))}
          </ul>
        </Card>
      )}

      {project.resumeBullets?.length > 0 && (
        <Card className="p-6">
          <SectionHeader title="ATS Resume Bullets">
            <CopyButton text={project.resumeBullets?.map(b => `• ${b}`).join("\n")} label="Copy Bullets" />
          </SectionHeader>

          <ul className="space-y-3">
            {project.resumeBullets.map((bullet, index) => (
              <li
                key={index}
                className="rounded border border-slate-200 p-3 text-sm text-slate-700 dark:border-slate-700 dark:text-slate-300"
              >
                • {bullet}
              </li>
            ))}
          </ul>
        </Card>
      )}

      {project.improvements?.length > 0 && (
        <Card className="p-6">
          <SectionHeader title="Improvement Suggestions">
            <CopyButton text={project.improvements?.join("\n")} label="Copy" />
          </SectionHeader>

          <ul className="space-y-3">
            {project.improvements.map((item, index) => (
              <li
                key={index}
                className="rounded border border-slate-200 p-3 text-sm text-slate-700 dark:border-slate-700 dark:text-slate-300"
              >
                💡 {item}
              </li>
            ))}
          </ul>
        </Card>
      )}

      {project.alternatives?.length > 0 && (
        <Card className="p-6">
          <SectionHeader title="Alternative Project Ideas" />

          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {project.alternatives.map((alt, index) => (
              <div
                key={index}
                className="rounded-lg border border-slate-200 p-4 dark:border-slate-700"
              >
                <h4 className="font-semibold text-slate-950 dark:text-white">{alt.title}</h4>
                <p className="mt-2 text-sm text-slate-600 dark:text-slate-400">{alt.description}</p>
                <span className="mt-3 inline-block rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold text-slate-700 dark:bg-slate-800 dark:text-slate-300">
                  {alt.difficulty}
                </span>
              </div>
            ))}
          </div>
        </Card>
      )}

      {project.techAdvisor && (
        <Card className="p-6">
          <SectionHeader title="Tech Stack Advisor" />

          <div className="space-y-4">
            {project.techAdvisor.recommendedFrontend?.length > 0 && (
              <div>
                <h4 className="mb-2 font-semibold text-slate-900 dark:text-white">Frontend</h4>
                <div className="flex flex-wrap gap-2">
                  {project.techAdvisor.recommendedFrontend.map((tech, idx) => (
                    <span key={idx} className="rounded-md bg-blue-100 px-3 py-1 text-sm font-medium text-blue-700 dark:bg-blue-900/50 dark:text-blue-300">
                      {tech}
                    </span>
                  ))}
                </div>
              </div>
            )}

            {project.techAdvisor.recommendedBackend?.length > 0 && (
              <div>
                <h4 className="mb-2 font-semibold text-slate-900 dark:text-white">Backend</h4>
                <div className="flex flex-wrap gap-2">
                  {project.techAdvisor.recommendedBackend.map((tech, idx) => (
                    <span key={idx} className="rounded-md bg-green-100 px-3 py-1 text-sm font-medium text-green-700 dark:bg-green-900/50 dark:text-green-300">
                      {tech}
                    </span>
                  ))}
                </div>
              </div>
            )}

            {project.techAdvisor.recommendedDatabase?.length > 0 && (
              <div>
                <h4 className="mb-2 font-semibold text-slate-900 dark:text-white">Database</h4>
                <div className="flex flex-wrap gap-2">
                  {project.techAdvisor.recommendedDatabase.map((tech, idx) => (
                    <span key={idx} className="rounded-md bg-purple-100 px-3 py-1 text-sm font-medium text-purple-700 dark:bg-purple-900/50 dark:text-purple-300">
                      {tech}
                    </span>
                  ))}
                </div>
              </div>
            )}

            {project.techAdvisor.deploymentSuggestions?.length > 0 && (
              <div>
                <h4 className="mb-2 font-semibold text-slate-900 dark:text-white">Deployment</h4>
                <div className="flex flex-wrap gap-2">
                  {project.techAdvisor.deploymentSuggestions.map((tech, idx) => (
                    <span key={idx} className="rounded-md bg-orange-100 px-3 py-1 text-sm font-medium text-orange-700 dark:bg-orange-900/50 dark:text-orange-300">
                      {tech}
                    </span>
                  ))}
                </div>
              </div>
            )}
          </div>
        </Card>
      )}
    </div>
  );
}
